# Use the alpine version of the devopsdockeruh/simple-web-service image as the base
FROM devopsdockeruh/simple-web-service:alpine

# Override the default command to run the 'server' command when the container starts
CMD server
